language: python
python:
  - "2.7"

notifications:
  email:
    on_success: change
    on_failure: change

env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=pylint

install:
  - pip install tox --use-mirrors
    # Install coveralls if python>2.5
  - if [[ "${TRAVIS_PYTHON_VERSION}" != "2.5" ]]; then pip install coveralls --use-mirrors && export COVERALLS=1; fi

script:
    # run the tests with coverage
  - tox -e $TOX_ENV

after_success:
  # run coveralls if it is installed
  - if [[ $COVERALLS ]]; then coveralls; fi
