language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.2"
  - "3.3"
matrix:
  allow_failures:
    - python:
      - "3.2"
      - "3.3"
notifications:
  email:
    on_success: change
    on_failure: change
install:
  - pip install -r requirements.txt --use-mirrors
    # Install any Python 3 or Python 2/PyPy specific requirements
  - if [[ "${TRAVIS_PYTHON_VERSION:0:1}" == "3" ]]; then pip install -r requirements/requirements_py3.txt --use-mirrors; else pip install -r requirements/requirements_py2.txt --use-mirrors; fi
  - pip install coverage --use-mirrors
    # Install the semetric-python library
  - pip install -e . --use-mirrors
    # Install unittest2 if python2 is being used or install unittest2py3k if python3 is being used
  - if [[ "${TRAVIS_PYTHON_VERSION:0:1}" == "3" ]]; then pip install unittest2py3k --use-mirrors; else pip install unittest2 --use-mirrors; fi
    # Install coveralls if python>2.5
  - if [[ "${TRAVIS_PYTHON_VERSION}" != "2.5" ]]; then pip install coveralls --use-mirrors && export COVERALLS=1; fi
script:
    # run the tests with coverage
  - nosetests --with-coverage --cover-package semetric.apiclient
after_success:
  # run coveralls if it is installed
  - if [[ $COVERALLS ]]; then coveralls; fi
