language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.2"
  - "3.3"
matrix:
  allow_failures:
    - python:
      - "3.2"
      - "3.3"
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install coverage --use-mirrors
    # Install the semetric-python library
  - pip install . --use-mirrors
    # Install unittest2 if python2 is being used
  - if [[ "${TRAVIS_PYTHON_VERSION:0:1}" -eq "2" ]]; then pip install unittest2 --use-mirrors; fi
    # Install unittest2py3k if python3 is being used
  - if [[ "${TRAVIS_PYTHON_VERSION:0:1}" -eq "3" ]]; then pip install unittest2py3k --use-mirrors; fi
    # Install coveralls if python>2.5
  - if [[ $TRAVIS_PYTHON_VERSION != "2.5" ]]; then pip install coveralls --use-mirrors && export COVERALLS=1; fi
script:
    # run the tests with coverage
  - nosetests --quiet --with-coverage --cover-package semetric.apiclient
after_success:
  # run coveralls if it is installed
  - if [[ $COVERALLS ]]; then coveralls; fi
